#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

VENV=venv

# Switch to base directory of this script
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ -f $VENV/freeze.txt ]
  then
    if md5sum -c $VENV/freeze.txt
      then
        echo "venv \"$VENV\" is update"
        exit 0;
    fi
fi

if [ -d $VENV ]
  then
    echo "Found old $VENV"
    rm -Rf $VENV
fi

WHEELHOUSE=""
if [ -d wheelhouse ]
  then
    echo "Found wheelhouse"
    WHEELHOUSE="-f wheelhouse "
fi

python -m venv --copies $VENV
if [ -x $VENV/bin/pip ]; then
  # MacOSX and Linux
  VENVPIP="$VENV/bin/pip"
else
  # Windows
  VENVPIP="$VENV/Scripts/python.exe -m pip"
fi

$VENVPIP install -U --no-index -f requirements $WHEELHOUSE setuptools
$VENVPIP install -U --no-index -f requirements $WHEELHOUSE pip
$VENVPIP install -U --no-index -f requirements $WHEELHOUSE -r requirements.txt

md5sum requirements.txt > $VENV/freeze.txt
