#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -ex

# Switch to base directory of this script
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

VENV=venv

if [ -d $VENV ]
  then
    echo "Found old $VENV"
    rm -Rf $VENV
fi

if [ -d requirements.old ]
  then
    echo "Removing old requirements.old"
    rm -Rf requirements.old
fi

if [ -d requirements ]
  then
    echo "Found existing requirements folder"
    mv requirements requirements.old
    OLDREQ="-f requirements.old "
fi

python -m venv --copies $VENV
if [ -x $VENV/bin/pip ]; then
  # MacOSX and Linux
  VENVPIP="$VENV/bin/pip"
else
  # Windows
  VENVPIP="$VENV/Scripts/python.exe -m pip"
fi
$VENVPIP install -U pip
$VENVPIP install -U setuptools
for req in requirements.*.txt
  do
    echo "Installing requirements from: $req"
    $VENVPIP install $OLDREQ -r $req
done

$VENVPIP freeze > requirements.txt
mkdir requirements
$VENVPIP install --download requirements $OLDREQ -r requirements.txt
$VENVPIP install --download requirements $OLDREQ pip
$VENVPIP install --download requirements $OLDREQ setuptools

./setup_venv

if [ -d requirements.old ]
  then
    echo "Removing requirements.old"
    rm -Rf requirements.old
fi
